### ISSUE TITLE
tolower() support

### ISSUE THREAD

**Issue by talKitron** [cristipufu/elasticsearch-odata-net#4]
https://github.com/cristipufu/elasticsearch-odata-net/blob/06c63e3a54a17a1f8b932d1a196cfa96f5015956/src/Nest.OData/ODataFilterExtensions.cs#L188

Hello

This doesn't consider the case of using OData Query Options, for example in case of an OData filter such as contains(tolower(someProperty), 'some string') - https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360993

**Comment by cristipufu** [comment]
Hi, the thing is that Elasticsearch's standard tokenizer automatically saves the values as lowercase, so when we [extract the value here from the OData query options](https://github.com/cristipufu/elasticsearch-odata-net/blob/master/src/Nest.OData/ODataFilterExtensions.cs#L303) we transform it to lowercase as well

**Comment by cristipufu** [comment]
fixed by https://github.com/cristipufu/elasticsearch-odata-net/pull/5
